Module1 task2
htmlacademy-yii/1025823-task-force-2 pull request #2
Opened 2021-07-27 15:14 UTC by rozhikhin

index.php - установка в параметрах сессии роли пользователя (для тестирования)

2021-07-28 07:27 UTC, olegmifle requested changes
Не хватает ещё проверок работоспособности.
Можно те же ассерты использовать как в примере

2021-07-28 07:27 UTC, olegmifle commented on src/Tack.php
> +    }
Вроде такого в задании нет. Зачем это?
Ну и, если это сеттер, то в аргументе сеттеру должны передаваться параметры. А то, что ты делаешь, нужно выносить в другой слой абстракции.

2021-07-28 07:27 UTC, olegmifle commented on src/Tack.php
> +            die('Нет доступных действий');
Выбрасывай исключение, вместо die.

2021-07-28 07:27 UTC, olegmifle commented on src/Tack.php
> +    private $statuses_map = [
Переменный должны быть в camelCase стиле, согласно PSR.

2021-07-28 07:27 UTC, olegmifle commented on src/Tack.php
> +        }
По заданию нужно организовать зависимость действия от статуса. Роль там не фигурирует.

2021-07-31 19:13 UTC, rozhikhin commented
Привет.
Я исправил вроде все

2021-08-04 18:53 UTC, olegmifle approved these changes

2021-08-04 18:53 UTC, merged